import "./lib/styles/globals.css";

export { App } from "./app";
export { AgentAvatar } from "./components/agent-avatar";
export { ChatInput } from "./components/chat-input";
export { ChatMessage } from "./components/chat-message";
export { ConnectionBanner } from "./components/connection-banner";
export { ConversationBadge } from "./components/conversation-badge";
export { ProjectPicker } from "./components/project-picker";
export { SettingsModal } from "./components/settings-modal";
export { Sidebar } from "./components/sidebar";
export type { Agent, ChatMessage as ChatMessageRecord, Conversation, ConversationKind, MessageStatus, Project, Setting } from "./db";
export { default as db } from "./db";
export { KNOWN_MODELS, knownWindowFor } from "./models";
export type { ModelInfo } from "./models";
export { createConnectionMonitor, hermesClient } from "./services/hermes";
export type { ConnectionMonitorCallbacks, SessionRecord, SessionSummary, StreamCallbacks, StreamMessage, StreamOptions, StreamUsage } from "./services/hermes";
export type { ChatState, ConnectionStatus, SlashCommand } from "./stores/chat";
export { useChatStore } from "./stores/chat";
export type { ProjectInput, ProjectsState } from "./stores/projects";
export { useProjectsStore } from "./stores/projects";
